language: ruby
before_install:
  - gem update --system
  - gem --version
rvm:
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - rake
  - rspec
  - sinatra
  - nokigiri
  - capybara
  - helloworld
